__pacakge_name__ = "gdalos"
__version__ = "0.50.0"
__author__ = "Idan Miara, Ben Avrahami"
__author_email__ = "idan@miara.com"
__license__ = "MIT"
__url__ = r"https://github.com/talos-gis/gdalos"
__description__ = "a simple gdal translate/warp/addo python wrapper for raster batch processing"
